src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("DateTime", message="Attention, le format renseigné n'est pas valide !")
     * @Assert\GreaterThan("today", message="La date d'arrivée doit être ultérieur à la date d'aujourd'hui", groups={"Front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("DateTime", message="Attention, le format renseigné n'est pas valide !")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ doit être supérieur à la date d'arrivée")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="integer")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="integer")
     */
    private $ttc_amount;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\PromoCode", inversedBy="booking")
     */
    private $promoCode;

    /**
     * Appelé à chaque création de réservation // Calcul le montant et initialise la date de création
     *
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function prePersist()
    {
        if (empty($this->createdAt)){
            $this->createdAt = new \DateTime();
        }
        if (empty($this->amount)){
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }

        if (empty($this->ttc_amount)){
            $this->ttc_amount = (($this->amount * 0.03) + $this->amount);
        }
    }

    public function getDuration()
    {
        $difference = $this->endDate->diff($this->startDate);

        return $difference->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

// Afficher le prix avec promocode

    public function promoAmount()
    {
        $promoCode = $this->getPromoCode();
        if($promoCode){
            if ($promoCode->getType() === 'POURCENTAGE'){
                $result = $this->ttc_amount - ($this->ttc_amount * $promoCode->getAmount() / 100);
            }else{
                $result = $this->ttc_amount - $promoCode->getAmount();
            }
        }
        return $result;
    }

    public function promoOperator()
    {
        $promoCode = $this->getPromoCode();
        if($promoCode){
            if ($promoCode->getType() === 'POURCENTAGE'){
                $operator = '%';
            }else{
                $operator = '€';
            }
        }
        return $operator;

    }

// FONCTIONS MANIPULATION DE DATE POUR LES RESERVATIONS
    public function isBookableDates()
    {
        // Dates impossible pour l'annonce
        $notAvailableDays = $this->ad->getNotAvailableDays();

        // On compare les dates choisies avec les dates impossibles
        $bookingDays = $this->getDays();

        $formatDay = function ($day) {
            return $day->format('Y-m-d');
        };
        // Tableau des journées en string
        $days = array_map($formatDay, $bookingDays);
        $notAvailable = array_map($formatDay, $notAvailableDays);

        foreach ($days as $day){
            if (array_search($day, $notAvailable) !== false) return false;
        }
        return true;
    }

    /**
     * Permet de récupérer un tableau des journéees qui correspondes à la réservation
     *
     * @return \DateTime[]
     */
    public function getDays()
    {
        $resultat = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24*60*60
        );
        $days = array_map(function ($dayTimestamp){
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);

        return $days;
    }

    public function getTtcAmount(): ?float
    {
        return $this->ttc_amount;
    }

    public function setTtcAmount(float $ttc_amount): self
    {
        $this->ttc_amount = $ttc_amount;

        return $this;
    }

    public function getPromoCode(): ?PromoCode
    {
        return $this->promoCode;
    }

    public function setPromoCode(?PromoCode $promoCode): self
    {
        $this->promoCode = $promoCode;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"email"}, message="Une autre utilisateur possède déjà cette email. Merci de le modifier")
 * @Vich\Uploadable
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var File|null
     * @Assert\Image(mimeTypes={"image/jpeg", "image/jpg", "image/png"}, mimeTypesMessage="Le format de votre fichier est invalide ({{ type }}). Formats acceptés: {{ types }}")
     * @Vich\UploadableField(mapping="user_image", fileNameProperty="avatarname")
     */
    private $imageFile;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatarname;


    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     * @Assert\NotBlank(message="Vous devez renseigner votre prénom")
     * @Assert\Length(min="2", minMessage="Le prénom doit faire au moin 2 caractères")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     * @Assert\NotBlank(message="Vous devez renseigner votre nom de famille")
     * @Assert\Length(min="2", minMessage="Le nom de famille doit faire au moin 2 caractères")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     * @Assert\Email(message="Veuillez renseigner un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez renseigner une URL valide pour votre avatar")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     * @Assert\Length(min="8", minMessage="Votre mot de passe doit faire au moins 8 caractères")
     */
    private $hash;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="Votre mot de passe n'a pa pu être confirmé. Veuillez réessayer...")
     */
    private $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     * @Assert\Length(min="10", minMessage="Votre introduction doit faire au moins 10 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text", nullable=false)
     * @Assert\Length(min="100", minMessage="Votre description doit faire au moins 100 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author", cascade={"remove"})
     *
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker", cascade={"remove"})
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Like", mappedBy="user", orphanRemoval=true)
     */
    private $likes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PromoCode", mappedBy="user")
     */
    private $promoCodes;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reset_token;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $token_updated_at;




    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->promoCodes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getPasswordConfirm()
    {
        return $this->passwordConfirm;
    }


    public function setPasswordConfirm($passwordConfirm): void
    {
        $this->passwordConfirm = $passwordConfirm;
    }


    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }
    /**
     * Permet d'initialiser le slug
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug()
    {
        if (empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->getLastName());
        }
    }

    public function getRoles()
    {
        $roles = $this->getUserRoles()->map(function ($role) {
            return $role->getTitle();
        })->toArray();

        $roles[] = 'ROLE_USER';

        return $roles;
    }

    public function getPassword()
    {
        return $this->hash;
    }

    public function getSalt()
    {
        return null;
    }

    public function getUsername()
    {
        return $this->getEmail();
    }

    public function eraseCredentials()
    {
    }

    public function getFullName()
    {
        return "{$this->firstName} {$this->lastName}";
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {

templates/booking/book.html.twig
{% extends 'base.html.twig' %}
{% block title %}Réserver l'annonce : {{ ad.title }}{% endblock %}
{% block stylesheets %}
    {{ encore_entry_link_tags('css/booking') }}
    {{ encore_entry_link_tags('css/date-picker') }}

    <style>
        .myControl{
            background-color: #faaf3a;
            border-radius: 1rem;
        }
        label{
            font-size: 1rem;
        }
        .montant{
            font-size: 1.3rem;
        }
        #taxe{
            text-decoration: none;
            color: #444;
        }
        #taxe:hover{
            color: #0c7cd5;

        }
        .mytext{
            font-size: 1rem;
        }


    </style>
{% endblock %}


{% block body %}
    <div class="container my-5">
        <h1 class="mb-2">Réserver pour l'annonce : <a href="{{ path('ads_show', {'slug': ad.slug}) }}">{{ ad.title }}</a></h1><br>
        <p class="mb-5 mytext">Vous êtes sur le point de réserver le bien de <strong><a href="{{ path('user_show', {'slug':ad.author.slug}) }}">{{ ad.author.fullName }}</a></strong>. Dites-nous tout on s'occupe du reste !</p>

        {{ form_start(form) }}
        <div class="myControl mb-4">
            <h2 class="mb-4">Commencez par nous dire quelles sont les dates qui vous intéressent !</h2>
            <div class="row">
                <div class="col">
                    {{ form_row(form.startDate) }}
                </div>
                <div class="col justify-content-between">
                    {{ form_row(form.endDate) }}
                </div>
            </div>
            <div class="mt-4">
                <h5 id="HT">Montant du séjour HT: <span id="amount" data-amount="0"></span></h5>
                <span id="days">0</span> <span id="nigths">nuit</span> à {{ ad.price }}&euro; / nuit
                <a id="taxe" href="{{ path('administrator_pages_cgv') }}"><h6 class="mt-3">*Taxe FlashBnB 3%</h6></a>
                <h5 class="mt-5 montant">Montant du séjour TTC: <span id="ttc" data-ttc="0"></span></h5>


                <div class="pb-0 mb-0 row justify-content-end">
                    <div class="col-12 col-md-6 col-lg-4">
                        <h6><label for="promocode" class="mr-1">Code promotion</label></h6>
                        <input id="promocode" class="form-control col-12" type="text" placeholder="Votre code de réduction">
                        <br><span id="promo_checker"></span>
                        <h5 class="mt-4 col-12 montant" id="promo_amount"></h5>
                    </div>
                    <br>
                </div><br>


            </div>

            <h4 class="mt-2">Vous avez un commentaire ?</h4>
            {{ form_row(form.comment) }}
        </div>
        <h2 class="mt-5 mb-3">Vous avez terminé !</h2>
        <p class="mytext">Vacances de rêves ? Espace Coworking ? Peu importe, on est avec vous !</p>
        <button type="submit" class="btn btn-primary mr-3">Je réserve</button>

        <a href="{{ path('ads_index')}}" class="btn btn-danger">Annuler</a>
        {{ form_end(form) }}
    </div>
{% endblock %}




{% block javascripts %}

    {{ encore_entry_script_tags('js/date-picker') }}
    <script>
        $(document).ready(e => {
            $('#booking_startDate, #booking_endDate').datepicker({
            format: 'dd/mm/yyyy',
            datesDisabled: [
                {% for day in ad.notAvailableDays %}
                    "{{ day.format('d/m/Y') }}",
                {% endfor %}
            ],
            startDate: new Date()
            });
            reservationAmount();
            $('#booking_startDate, #booking_endDate').change(reservationAmount)
        });
        
        function reservationAmount() {

            //Regex (\d+)\/(\d+)\/(\d{4})
            const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            const numberFormat = new Intl.NumberFormat("fr-FR", {maximumFractionDigits : '0'})

            if (startDate && endDate && startDate < endDate){
                const DAY_TIME = 24 * 60 * 60 * 1000;
                const interval = endDate.getTime() - startDate.getTime();
                const days = interval / DAY_TIME;
                const amount = days * {{ ad.price }};

                $('#days').text(days);
                //$('#amount').text(numberFormat.format(amount)).data('amount', amount);
                $('#amount').text(parseInt(amount) + ' €');
                //$('#ttc').text(numberFormat.format(((amount * 0.03) + amount))).data('ttc', ((amount * 0.03) + amount))
                $('#ttc').text(parseInt(((amount * 0.03) + amount)) + ' €')
                if (days > 1){
                    $('#nigths').text('nuits')
                }else{
                    $('#nigths').text('nuit')
                }
            }else{
                $('#days').text('0');
                $('#amount').text('');
                $('#ttc').text('');
                $('#nigths').text('nuit');
            }
        }
    </script>


    <script>
        // Gerer le promocode AJAX

        var promoCodeTextInit = function () {
            const promo_checker = document.getElementById('promo_checker')
            const promo_amount = document.getElementById('promo_amount')
            const booking_promoCode = document.getElementById('booking_promo_id')
            promo_checker.style.color = 'red'
            promo_amount.textContent =  ''
            booking_promoCode.value = ''

        }


        function onChangePromoCode(event){

            const url = "/promocode/checker";
            const promo_checker = document.getElementById('promo_checker')
            const promo_code = document.getElementById('promocode').value
            const promo_amount = document.getElementById('promo_amount')
            const booking_promoCode = document.getElementById('booking_promo_id')
            if (this.value === ''){
                promo_checker.textContent =  ''
                promo_amount.textContent =  ''
                booking_promoCode.value = ''
                return
            }

            axios.get(url).then(function (response) {
                const data = response.data.promoCodes
                if (data.length === 0){
                    promo_checker.textContent = 'Code invalide'
                    promoCodeTextInit()
                    return;
                }


                for (i = 0; i<= data.length; i ++){
                    if (data[i]['code'] !== promo_code){
                        promo_checker.textContent = 'Code invalide'
                        promoCodeTextInit()

                    }else{
                        const currentData = data[i]
                        if (currentData['expiredAt'] && currentData['expiredAt'] < Date.now()){
                            promo_checker.textContent = 'Code expiré'
                            promoCodeTextInit()
                            return;
                        }else{
                            if (currentData['maxNumber'] === -1){
                                promo_checker.textContent = "Ce code promotion n'est plus utilisable"
                                promoCodeTextInit()
                                return;
                            }else{
                                type = "%"
                                if (currentData['type'] === "FIXE"){
                                    type = "€"
                                }
                                promo_checker.textContent = "Code valide, vous bénéficiez d'une réduction de " + parseInt(currentData['amount']) + ' ' + type
                                promo_checker.style.color = 'green'
                                booking_promoCode.value = currentData['id']
                                amount = $('#ttc').text();
                                amount = parseInt(amount)


                                if (amount){
                                    if (type === '%'){
                                        amount = amount  - (amount * currentData['amount'] / 100)

                                    }else{
                                        amount = amount - currentData['amount']

                                    }
                                    if ( $('#booking_startDate').val() && $('#booking_endDate').val()){
                                        promo_amount.textContent = 'Montant après promotion: ' + parseInt(amount) + ' €'
                                    }
                                }
                                return;
                            }
                        }
                    }
                }


            }).catch( function (error) {
                if (error.response){
                    if (error.response.status >= 500){
                        promo_checker.textContent = "Une erreur est survenue, vérification impossible veuillez réessayer plus tard"
                    }
                }
            })
        }
        $('#promocode').keyup(onChangePromoCode).blur(onChangePromoCode).focus(onChangePromoCode).change(onChangePromoCode);
        $(window).ready(onChangePromoCode)
    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}Réservation n°{{ booking.id }}{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/booking.css') }}">
    <link rel="stylesheet" href="{{ asset('css/app.scss') }}">
    <style>
        .form-control{
            background-color: white;
        }
    </style>
{% endblock %}


{% block body %}

    {% set ad = booking.ad %}
    {% set author = booking.ad.author %}
    <div class="container">
        <h1>Votre réservation (n°{{ booking.id }})</h1>

        {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">
                <h4 class="alert-heading">Bravo !</h4>
                <p>
                    Votre réservation auprès de
                    <strong>
                        <a href="{{ path('user_show', {'slug': author.slug}) }}">{{ author.fullName }}</a>
                    </strong>
                    pour l'annonce
                    <strong>
                        <a href="{{ path('ads_show', {'id': ad.id, 'slug': ad.slug}) }}">{{ ad.title }}</a>
                    </strong>
                    a bien été prise en compte !
                </p>
            </div>
        {% endif %}
        <div class="row">
            <div class="col">
                <div class="myControl">
                    <h2 class="mt-3">Détails</h2>
                    <dl class="row">
                        <dt class="col-md-4">Numéro</dt>
                        <dd class="col-md-8">{{ booking.id }}</dd>
                        <dt class="col-md-4">Date d'arrivée</dt>
                        <dd class="col-md-8">{{ booking.startDate|date('d/m/Y') }}</dd>
                        <dt class="col-md-4">Date de départ</dt>
                        <dd class="col-md-8">{{ booking.endDate|date('d/m/Y') }}</dd>
                        <dt class="col-md-4">Nombre de nuits</dt>
                        <dd class="col-md-8">{{ booking.duration }}</dd>
                        <dt class="col-md-4">Montant Total HT</dt>
                        <dd class="col-md-8">{{ booking.amount }} &euro;</dd>
                        <dt class="col-md-4">Taxe FlashBnB</dt>
                        <dd class="col-md-8">3%</dd>
                        <dt class="col-md-4">Montant Total TTC</dt>
                        <dd class="col-md-8">{{ booking.ttcAmount }} &euro;</dd>
                        {% if booking.promoCode %}
                            <dt class="col-md-4">Code promotion</dt>
                            <dd class="col-md-8">{{ booking.promoCode.code }}</dd>
                            <dt class="col-md-4">Réduction</dt>
                            <dd class="col-md-8">{{ booking.promoCode.amount }} {{ booking.promoOperator }}</dd>
                            <dt class="col-md-4">Montant après réduction</dt>
                            <dd class="col-md-8">{{ booking.promoAmount }} &euro;</dd>
                        {% endif %}
                        <dt class="col-md-4">Commentaire</dt>
                        <dd class="col-md-8">{{ booking.comment |default('Aucun commentaire')|raw }}</dd>
                    </dl>

                    <hr>

                    <h2 class="alert-heading">Votre hôte</h2>
                    <div class="row my-4">
                        <div class="col-3 text-center">
                            <img src="{{ author.picture }}" class="avatar avatar-medium" alt="{{ author.fullName }}">
                        </div>
                        <div class="col px-0">
                            <h4>
                                <a href="{{ path('user_show', {'slug': author.slug}) }}">{{ author.fullName }}</a>
                            </h4>
                            <span class="badge badge-primary">{{ author.ads|length }} annonces</span>
                        </div>
                    </div>
                    {{ author.description|raw }}
                    <a href="{{ path('user_show', {'slug': author.slug}) }}" class="btn btn-primary">Plus d'infos sur {{ author.firstname }}</a>
                </div>
                <div class="alert alert-warning mt-5" id="comment">
                    <h2 class="alert-heading">Votre avis compte !</h2>
                    {% if date() > date(booking.endDate) %}
                        {% set comment = booking.ad.commentFromAuthor(app.user) %}
                        {% if comment is not null %}
                            <blockquote>
                                {{ comment.content }}
                            </blockquote>
                            <strong>Note : </strong> {% include 'common/rating.html.twig' with {'rating': comment.rating } %}
                        {% else %}
                            {{ form_start(form) }}
                            {{ form_widget(form) }}
                            <button type="submit" class="btn btn-primary">Confirmer</button>
                            {{ form_end(form) }}
                        {% endif %}
                    {% else %}
                        <p>Revenez noter cette annonce lorsque votre séjour sera terminé !</p>
                    {% endif %}
                </div>
            </div>
            <div class="col">
                <div class="myControl">
                    <h2 class="alert-heading">Votre hébergement</h2>
                    <h4>
                        <a href="{{ path('ads_show', {'id': ad.id, 'slug': ad.slug}) }}">{{ ad.title }}</a>
                    </h4>
                    <img class="img-fluid" src="{{ ad.coverImage }}" alt="Image de {{ ad.title }}">
                    {{ ad.content|raw }}
                    <a href="{{ path('ads_show', {'id': ad.id, 'slug': ad.slug}) }}" class="btn btn-primary">Plus d'informations</a>
                </div>
            </div>

        </div>
    </div>

{% endblock %}