src/Entity/Ad.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;




/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"title", "slug"},
 *     message="Une autre annonce possède déjà ce titre. Merci de le modifier")
 * @Vich\Uploadable
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var File|null
     * @Assert\Image(mimeTypes={"image/jpeg", "image/jpg", "image/png"}, mimeTypesMessage="Le format de votre fichier est invalide ({{ type }}). Formats acceptés: {{ types }}")
     * @Vich\UploadableField(mapping="ad_cover_image", fileNameProperty="adCoverImage")
     */
    private $imageFile2;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adCoverImage;


    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="10", max="255",
     *     minMessage="Le titre doit faire plus de 10 caractères",
     *     maxMessage="Le tite ne peut pas faire plus de 50 caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive(message="Le prix ne peut pas être négatif")
     * @Assert\GreaterThanOrEqual(value="50" ,message="Le prix ne peut pas être inférieur à 50€ par nuits")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min="10", minMessage="Votre introduction ne peut pas faire moin de 20 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min="100", minMessage="Votre description détaillée ne peut pas faire moin de 100 caractères")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive(message="Le nombre de chambre ne peut pas être négatif")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true, cascade={"persist"})
     * @Assert\Valid()
     */
    private $images;

    /**
     * @Assert\All({
     *     @Assert\Image(mimeTypes={"image/jpeg", "image/jpg", "image/png"}, mimeTypesMessage="Le format de votre fichier est invalide ({{ type }}). Formats acceptés: {{ types }}")
     * })
     */
    private $imageFiles;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad", cascade={"remove"})
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="float", scale=4, precision=6)
     */
    private $lat;

    /**
     * @ORM\Column(type="float", scale=4, precision=7)
     */
    private $lng;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $street_address;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="ads")
     */
    private $options;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Like", mappedBy="ad", orphanRemoval=true)
     */
    private $likes;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;


    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->y = new ArrayCollection();
        $this->options = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug avec cycle de vie
     *
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug()
    {
        if (empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Permet de récupérer le commentaire d'un auteur par rapport à une annonce
     *
     * @param User $author
     * @return mixed|null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach ($this->comments as $comment){
            if ($comment->getAuthor() === $author) return $comment;
        }
        return null;
    }

    /**
     * Permet d'obtenir la moyenne des notes pour cette annonce
     *
     * @return float|int
     */
    public function getAvgRatings()
    {
        // somme des notations
        $sum = array_reduce($this->comments->toArray(), function ($total, $comment){
            return $total + $comment->getRating();
        }, 0);

        // Division pour la moyenne
        if (count($this->comments) > 0) return $sum / count($this->comments);
        return 0;
    }
    
    /**
     * Permet d'obtenir un tableau des jours indisponibles pour cette annonce
     *
     * @return array
     */
    public function getNotAvailableDays()
    {
        $notAvailableDays = [];
        foreach ($this->bookings as $booking){
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                (24*60*60)
            );
            $days = array_map(function ($dayTimestamp){
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }
        return $notAvailableDays;
    }

    /**
     * Permet de savoir si un article est liké par un utilisateur
     * @param User $user
     * @return bool
     */
    public function isLikeByUser(User $user)
    {
        foreach ($this->likes as $like){
            if ($like->getUser() === $user ) return true;
        }
        return false;
    }
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */

templates/common/_ad.html.twig
{% set url = path('ads_show', { 'slug': ad.slug }) %}
<div class="col-md-4">
    <div class="card card2 mb-3">
        <div class="row no-gutters">
            <div class="col-md-12 px-2 py-2">
                <a href="{{ url }}">
                    {% if ad.adCoverImage %}
                        <img class="img_card rounded" src="{{ vich_uploader_asset(ad, 'imageFile2') }}" alt="Image de l'appartement pour l'annonce {{ ad.title }}" style="height: 100%; min-height: 180px; width: 100%; display: block">
                    {% elseif not ad.adCoverImage and ad.coverImage %}
                        <img class="img_card rounded" src="{{ ad.coverImage }}" alt="Image de l'appartement pour l'annonce {{ ad.title }}" style="height: 100%; min-height: 180px; width: 100%; display: block">
                    {% else %}
                        <img class="img_card rounded" src="{{ asset('images/ads_cover_images/cover_image_default.jpeg')|imagine_filter('card') }}" alt="Image de l'appartement pour l'annonce {{ ad.title }}" style="height: 100%; min-height: 180px; width: 100%; display: block">
                    {% endif %}
                </a>
            </div>
            <div class="col-md-12">
                <div class="card-header text-center">
                    {{ ad.rooms }} chambres, <strong>{{ ad.price }}&euro; / nuit</strong><br>
                    <span class="card-text">
                        {{ ad.city }} ({{ ad.postalCode|replace({' ':''}) }})
                    </span><br>
                    {% if ad.comments|length > 0 %}
                        {% include 'common/rating.html.twig' with{'rating' : ad.avgRatings} %}
                    {% else %}
                        <small>Pas encore noté</small>
                    {% endif %}
                </div>
                <div class="card-body cutCard">
                    <a href="{{ url }}">
                        <h4 class="card-title">{{ ad.title }}</h4>
                    </a>
                    <p class="card-text">
                        {% if ad.introduction|length > 50 %}
                            {{ ad.introduction|slice(0, 100) }}...
                        {% else %}
                            {{ ad.introduction }}
                        {% endif %}
                    </p>
                    <div class="row justify-content-between align-items-center px-3">
                        <a class="js-like" href="{{ path('ads_like', {'slug': ad.slug}) }}">
                            {% if app.user and ad.isLikeByUser(app.user) %}
                                <i class="fas fa-heart" style="color: red"></i>
                            {% else %}
                                <i class="far fa-heart" style="color: red"></i>
                            {% endif %}
                            <span class="js-likes">{{ ad.likes|length }}</span>
                        </a>
                        {% if app.user and app.user == ad.author %}
                            {% include 'common/_editButton.html.twig' with {
                                'route': 'ads_edit',
                                'id': ad.id,
                                'slug':ad.slug,
                                'btn':'warning',
                                'type':'badge'
                            } %}
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

templates/common/_ad2.html.twig
{% set url = path('ads_show', { 'slug': ad.slug }) %}
<div class="col-lg-4 card_container" data-mapping="{{ ad.id }}">
    <div class="card card2 mb-3">
        <div class="row no-gutters">
            <div class="col-12 col-md-5 col-lg-12 img_card_container px-2 py-2">
                <a href="{{ url }}">
                    {% if ad.adCoverImage %}
                        <img class="img_card rounded" src="{{ vich_uploader_asset(ad, 'imageFile2') }}" alt="Image de l'appartement pour l'annonce {{ ad.title }}" style="height: 100%; min-height: 180px; width: 100%; display: block">
                    {% elseif not ad.adCoverImage and ad.coverImage %}
                        <img class="img_card rounded" src="{{ ad.coverImage }}" alt="Image de l'appartement pour l'annonce {{ ad.title }}" style="height: 100%; min-height: 180px; width: 100%; display: block">
                    {% else %}
                        <img class="img_card rounded" src="{{ asset('images/ads_cover_images/cover_image_default.jpeg')|imagine_filter('card') }}" alt="Image de l'appartement pour l'annonce {{ ad.title }}" style="height: 100%; min-height: 180px; width: 100%; display: block"">
                    {% endif %}
                </a>
            </div>
            <div class="col-12 col-md-7 col-lg-12 body_card_container">
                <div class="card-header text-center">
                    {{ ad.rooms }} chambres, <strong>{{ ad.price }}&euro; / nuit</strong><br>
                    <span class="card-text">
                        {{ ad.city }} ({{ ad.postalCode|replace({' ':''}) }})
                    </span><br>
                    {% if ad.comments|length > 0 %}
                        {% include 'common/rating.html.twig' with{'rating' : ad.avgRatings} %}
                    {% else %}
                        <small>Pas encore noté</small>
                    {% endif %}
                </div>
                <div class="card-body cutCard">
                    <a href="{{ url }}">
                        <h4 class="card-title">{{ ad.title }}</h4>
                    </a>
                    <p class="card-text">
                        {% if ad.introduction|length > 50 %}
                            {{ ad.introduction|slice(0, 100) }}...
                        {% else %}
                            {{ ad.introduction }}
                        {% endif %}
                    </p>

                    <div class="row justify-content-between align-items-center px-3">
                        <a class="js-like" href="{{ path('ads_like', {'slug': ad.slug}) }}">
                            {% if app.user and ad.isLikeByUser(app.user) %}
                                <i class="fas fa-heart" style="color: red"></i>
                            {% else %}
                                <i class="far fa-heart" style="color: red"></i>
                            {% endif %}
                            <span class="js-likes">{{ ad.likes|length }}</span>
                        </a>
                        {% if app.user and app.user == ad.author %}
                            {% include 'common/_editButton.html.twig' with {
                                'route': 'ads_edit',
                                'id': ad.id,
                                'slug':ad.slug,
                                'btn':'warning',
                                'type':'badge'
                            } %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/common/_editButton.html.twig
<form class="my-1" method="post" action="{{ path(route, {'slug': slug}) }}">
    <input type="hidden" name="_method" value="EDIT">
    <input type="hidden" name="_token_edit" value="{{ csrf_token('edit' ~ id ) }}">
    <button class="{{ type|default('btn') }} {{ type|default('btn') }}-{{ btn|default('primary') }} ">Modifier l'annonce</button>
</form>

templates/common/_suggest.html.twig
{% set url = path('ads_show', { 'slug': ad.slug }) %}
<div class="col-10 col-sm-8 col-md-6 col-lg-8 col-xl-4 card-cell" data-mapping="{{ ad.id }}">
    <div class="card card2 mb-3">
        <div class="row no-gutters">
            <div class="col-12 col-lg-5 col-xl-12 img_card_container px-2 py-2">
                <a href="{{ url }}">
                    {% if ad.adCoverImage %}
                        <img class="img_card rounded" src="{{ vich_uploader_asset(ad, 'imageFile2') }}" alt="Image de l'appartement pour l'annonce {{ ad.title }}" style="height: 100%; min-height: 180px; width: 100%; display: block">
                    {% elseif not ad.adCoverImage and ad.coverImage %}
                        <img class="img_card rounded" src="{{ ad.coverImage }}" alt="Image de l'appartement pour l'annonce {{ ad.title }}" style="height: 100%; min-height: 180px; width: 100%; display: block">
                    {% else %}
                        <img class="img_card rounded" src="{{ asset('images/ads_cover_images/cover_image_default.jpeg')|imagine_filter('card') }}" alt="Image de l'appartement pour l'annonce {{ ad.title }}" style="height: 100%; min-height: 180px; width: 100%; display: block">
                    {% endif %}
                </a>
            </div>
            <div class="col-12 col-lg-7 col-xl-12 body_card_container">
                <div class="card-header text-center">
                    {{ ad.rooms }} chambres, <strong>{{ ad.price }}&euro; / nuit</strong><br>
                    <span class="card-text">
                        {{ ad.city }} ({{ ad.postalCode|replace({' ':''}) }})
                    </span><br>
                    {% if ad.comments|length > 0 %}
                        {% include 'common/rating.html.twig' with{'rating' : ad.avgRatings} %}
                    {% else %}
                        <small>Pas encore noté</small>
                    {% endif %}
                </div>
                <div class="card-body cutCard">
                    <a href="{{ url }}">
                        <h4 class="card-title">{{ ad.title }}</h4>
                    </a>
                    <p class="card-text">
                        {% if ad.introduction|length > 50 %}
                            {{ ad.introduction|slice(0, 100) }}...
                        {% else %}
                            {{ ad.introduction }}
                        {% endif %}
                    </p>

                    <div class="row justify-content-between align-items-center px-3">
                        <a class="js-like" href="{{ path('ads_like', {'slug': ad.slug}) }}">
                            {% if app.user and ad.isLikeByUser(app.user) %}
                                <i class="fas fa-heart" style="color: red"></i>
                            {% else %}
                                <i class="far fa-heart" style="color: red"></i>
                            {% endif %}
                            <span class="js-likes">{{ ad.likes|length }}</span>
                        </a>
                        {% if app.user and app.user == ad.author %}
                            {% include 'common/_editButton.html.twig' with {
                                'route': 'ads_edit',
                                'id': ad.id,
                                'slug':ad.slug,
                                'btn':'warning',
                                'type':'badge'
                            } %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/common/carousel.html.twig
<div id="carouselExampleIndicators" class="carousel slide mt-4" data-ride="carousel">
    <ol class="carousel-indicators">
        {% for image in ad.images %}
            <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}"
                class="{% if loop.first %}active{% endif %}"></li>
        {% endfor %}
    </ol>
    <div class="carousel-inner">
        {% for image in ad.images %}
            <div class="carousel-item{% if loop.first %} active{% endif %}">
                {% if not image.url %}
                    <img class="d-block w-100 carouselImg" src="{{ vich_uploader_asset(image, 'imageFile') }}" alt="First slide" style="min-height: 476.25px">
                {% else %}
                    <img class="d-block w-100" src="{{ image.url }}" alt="First slide">
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
       data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
       data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

templates/common/flashes.html.twig
{% for label, messages in app.flashes  %}
    <div class="container">
        <div class="alert alert-{{ label }} text-center">
            {% for message in messages  %}
                {{ message|raw }}
            {% endfor %}
        </div>
    </div>
{% endfor %}

templates/common/footer.html.twig
<footer class="mt-5 bg-dark py-5 text-center text-light">
    <div class="row my-5 py-5">
        <div class="col">
            <a class="footerLink" target="_blank" href="{{ path('administrator_pages_qsm') }}">Qui sommes nous ?</a>
        </div>
        <div class="col">
            <a class="footerLink" target="_blank" href="{{ path('administrator_pages_cgv') }}">Conditions générales des ventes</a>
        </div>
        <div class="col">
            <a class="footerLink" target="_blank" href="{{ path('administrator_pages_infoFlashbnb') }}">FlashBnb - Informations</a>
        </div>
        <div class="col">
            <a class="footerLink" target="_blank" href="{{ path('administrator_pages_mentionsLegales') }}">Mentions légales</a>
        </div>
        <div class="col">
            <a class="footerLink" target="_blank" href="{{ path('administrator_pages_contact') }}">Nous contacter</a>
        </div>
        <div class="col">
            <a class="footerLink" target="_blank" href="{{ path('administrator_pages_newsletter') }}">S'inscrire à la newsletter</a>
        </div>
        <div class="col">
            <a class="footerLink" target="_blank" href="{{ path('administrator_pages_plan') }}">Plan du site</a>
        </div>
    </div>
    <div class="row justify-content-start">
        <div class="col-6 text-left px-5 mx-4">
            <span style="font-size: 1rem">Nous suivre:</span>
            <a class="socialNetworkFooter px-1" href="https://twitter.com/" target="_blank"><i class="fab fa-twitter" style="color: #00B6F1;"></i></a>
            <a class="socialNetworkFooter px-1" href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook" style="color: #3B5998;"></i></a>
            <a class="socialNetworkFooter px-1" href="https://www.whatsapp.com/?lang=fr" target="_blank"><i class="fab fa-whatsapp" style="color: #25d366;"></i></a>
            <a class="socialNetworkFooter px-1" href="https://www.linkedin.com/" target="_blank"><i class="fab fa-linkedin-in" style="color: #04669A;"></i></a>
            <a class="socialNetworkFooter px-1" href="https://www.instagram.com/?hl=fr" target="_blank"><i class="fab fa-instagram" style="color: #c13584"></i></a>
            <a class="socialNetworkFooter px-1" href="https://www.snapchat.com/l/fr-fr/" target="_blank"><i class="fab fa-snapchat" style="color: #fffc00;"></i></a>
        </div>
    </div>
    <br><p class="my-5" style="font-size: 1rem">Copyright FlashBnB</p>
</footer>

templates/common/header.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ path('home') }}"><img id="logoFlashbnb" src="{{ asset('images/logo/logo_flashbnb_vecto_grey.png') }}" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03"
            aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor03">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ path('home') }}">Acceuil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('ads_index') }}">Annonces</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('ads_create') }}">Créer une annonce</a>
            </li>
            {% if app.user %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('user_show', {'slug':app.user.slug }) }}">Mon Compte</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('account_bookings') }}">Mes réservations</a>
                </li>h
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('user_show', {'slug':app.user.slug, '_fragment':'liked' }) }}">Mes favoris</a>
                </li>
            {% endif %}
        </ul>
        <form id="searchForm" class="form-inline my-2 my-lg-0">
            <input id="searchBarre" class="form-control mr-sm-2" type="search" placeholder="Rechercher" aria-label="Search">
            <button id="searchButton" class="btn btn-outline-warning my-2 my-sm-0 d-block d-md-none d-xl-block" type="submit">Rechercher</button>
        </form>
        <ul class="navbar-nav ml-auto">
            {% if app.user %}
                {% if 'ROLE_ADMIN' in app.user.roles %}
                    <li class="nav-item d-flex align-items-center">
                        <a href="{{ path('admin_dashboard') }}" class="nav-link">
                            <i class="fas fa-tasks mr-1"></i>Administration
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="accountDropdownLink">
                        {% if app.user.avatarname %}
                            <img src="{{ vich_uploader_asset(app.user, 'imageFile')}}" class="avatar avatar-mini" alt="Avatar de {{ app.user.fullName }}"> {{ app.user.fullName }}
                        {% elseif not app.user.avatarname and app.user.picture %}
                            <img src="{{ app.user.picture }}" class="avatar avatar-mini" alt="Avatar de {{ app.user.fullName }}"> {{ app.user.fullName }}
                        {% else %}
                            <img src="{{ asset('images/user/avatar_default.jpeg') }}" class="avatar avatar-mini" alt="Avatar de {{ app.user.fullName }}"> {{ app.user.fullName }}
                        {% endif %}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="accountDropdownLink">
                        <a href="{{ path('ads_create') }}" class="dropdown-item">Créer une annonce</a>
                        <div class="dropdown-divider"></div>
                        <a href="{{ path('account_index') }}" class="dropdown-item">Mon compte</a>
                        <a href="{{ path('user_show', {'slug':app.user.slug, '_fragment':'liked' }) }}" class="dropdown-item">Mes favoris</a>
                        <a href="{{ path('account_bookings') }}" class="dropdown-item">Mes réservations</a>
                        <a href="{{ path('account_profil') }}" class="dropdown-item">Modifier mon profil</a>
                        <div class="dropdown-divider"></div>
                        <a href="{{ path('account_logout') }}" class="dropdown-item">Déconnexion</a>
                    </div>
                </li>

            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('account_register') }}">Inscription</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('account_login') }}">Connexion</a>
                </li>
            {% endif %}

        </ul>
    </div>
</nav>

templates/common/pagination.html.twig
<div class="d-flex justify-content-center">

        {% if pages == 0 %}
            <div class="mt-5 text-center">
                <i class="far fa-frown pb-3" style="font-size: 10rem"></i>
                <h4>Nous n'avons trouvé aucun résultats...<br><br> Veuillez changer vos paramètres de recherche ou
                    <a href="{{ path('ads_index') }}">cliquez ici</a> pour réinitialiser
                </h4>
            </div>
        {% else %}
            <ul class="pagination">
                <li class="page-item {% if page == 1 %} disabled {% endif %}">
                    <a class="page-link" href="{{ path(route, {'page': page - 1}) }}">&laquo;</a>
                </li>
            {% for i in 1..pages %}
                <li class="page-item {% if page == i %} active {% endif %}">
                    <a class="page-link" href="{{ path(route, {'page': i}) }}">{{ i }}</a>
                </li>
            {% endfor %}
                <li class="page-item {% if page == pages %} disabled {% endif %}">
                    <a class="page-link" href="{{ path(route, {'page': page + 1}) }}">&raquo;</a>
                </li>
            </ul>
        {% endif %}
</div>

templates/common/rating.html.twig
<span class="rating">
{% for i in 1..5 %}
    {% if i <= rating %}
        <i class="fas fa-star"></i>
               {% else %}
        <i class="far fa-star"></i>
    {% endif %}
{% endfor %}
</span>